### ISSUE TITLE
Perhaps merge with https://github.com/erkmos/haskell-companies?

### ISSUE THREAD

**Issue by ajnsit** [sigrlami/haskellcosm#1]
As the title says, there's already a list for haskell-companies. This project seems to be broader in its goals, but perhaps there is a way to collaborate?

**Comment by sigrlami** [comment]
Hi @ajnsit, actually I started collecting it in 2014 with this gist https://gist.github.com/sigrlami/769f5e6674adbd399f00/revisions?page=4 and even tried to collaborate on a project you mentioned https://github.com/erkmos/haskell-companies/issues/5 but didn't get enough feedback.

**Comment by ajnsit** [comment]
Ah that's unfortunate! I think some of the objections to using CSV are correct (lack of links etc.), but raw data is so much nicer to have when integrating with a website or something.

Have you considered adding a webpage to provide a nicer view for this data? I was just planning on getting started on a similar project to provide a [list of the people working in FP](https://github.com/ajnsit/fp-freelancers) using my [Concur](https://github.com/ajnsit/purescript-concur) UI toolkit.

**Comment by sigrlami** [comment]
@ajnsit Yes, I'm working on a small webapp already. In [analysis](https://github.com/sigrlami/haskellcosm/tree/master/app/analysis) directory I started small app with `dbfunctor` that can query raw `csv` data already. My goal is to have raw data, including projects that aren't active, and tooling to analyse raw data, produce analytics and make it easier for other people to update it.

**Comment by ajnsit** [comment]
Thanks for the info! Closing this.
